site:
  title: Alex H
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://ahogen.github.io
  start_page: blog::index.adoc
content:
  sources:
  - url: https://192.168.5.121:3000/alex/antora-blog-content.git
    branches: init
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
